name: GGvGoons
version: '${version}'
main: com.tyler.ggvsgoons.GGvGPlugin
api-version: '1.21'
author: Tyler

commands:
  warprisoner:
    description: Take a player as a war prisoner
    usage: /<command> <player>
  warprisoneraccept:
    description: Accept a war prisoner offer (internal)
    usage: /<command> <captorId>
  warprisonerdecline:
    description: Decline a war prisoner offer (internal)
    usage: /<command> <captorId>
  freeprisoner:
    description: Release your war prisoner
    usage: /<command> <player>
  executeprisoner:
    description: Execute your war prisoner
    usage: /<command> <player>
